# [project]
# name = "minghu6"
# version = "0.0.1"
# dynamic = ["dependencies"]

# [tool.setuptools]
# dynamic = { dependencies = { file = ["requirements.txt"] } }
# packages = { find = {} }  # implicit all

[tool.black]
line-length = 72
target-version = ['py312']

[tool.autopep8]
max_line_length = 72
ignore = ["E266"]
