#!/usr/bin/env bash


# shellcheck disable=SC2034
_m6ff()
{
    local cur prev words cword
    _compatible_comp_initialize "$@" || return

    local tags
    local cmd_i=1
    _sub_ff
}

complete -F _m6ff m6ff
